logging:
  level: INFO
  loggers:
    groep4.inf2b.hsleiden.nl: DEBUG

assets:
  overrides:
    /: frontend/dist

database:
  driverClass: org.postgresql.Driver
  user: postgres
  password: ipsen12345
  url: jdbc:postgresql://localhost:5432/ipose
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.hbm2ddl.auto: update
  maxWaitForConnection: 1s
  validationQuery: "/* MyService Health Check */ SELECT 1"
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
#logging:
#  level: DEBUG
#  # Logger-specific levels.
#  loggers:
#    org.hibernate.SQL: ALL
server:
  rootPath: /api/*